name: Common CI Workflow

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: "lts/*"

    secrets:
      NEXT_PUBLIC_SANITY_PROJECT_ID:
        required: true
      NEXT_PUBLIC_SANITY_DATASET:
        required: true
      NEXT_PUBLIC_BASE_URL:
        required: true
      NEXT_PUBLIC_RSS_API_URL:
        required: true
      NEXT_PUBLIC_MEDIUM_URL:
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
      NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
      NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
      NEXT_PUBLIC_RSS_API_URL: ${{ secrets.NEXT_PUBLIC_RSS_API_URL }}
      NEXT_PUBLIC_MEDIUM_URL: ${{ secrets.NEXT_PUBLIC_MEDIUM_URL }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
