name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/workflows/common.yml
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check code formatting
        run: npm run format:check
      - name: Lint code
        run: npm run lint
      - name: Typecheck code
        run: npm run typecheck
      - name: Test code
        run: npm test
      - name: Build code
        run: npm run build --if-present
