name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      node-version: "22.x"
    secrets: inherit

  lint-check:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check code formatting
        run: npm run format:check
      - name: Lint code
        run: npm run lint
      - name: Typecheck code
        run: npm run typecheck
      - name: Test code
        run: npm test
